### ISSUE TITLE
Flyweight unit tests

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-maven-plugin#1]
Generator should also generate unit tests for generated flyweights

**Comment by cmebarrow** [comment]
The generated tests should include the following for each structure member (or union member):
- set should succeed with valid value (include all set method variants)
- set should fail with value too small (for integer field) or value too short (for fixed length octets)
- set should fail with value too large (for integer field) or value too long (for fixed length octets)
- set should fail if it would result in limit exceeding maxLimit
- set should fail for string field if the value is too long (e.g. GT 255 for StringFW, GT 0xFFFF for String16FW)

**Comment by jfallows** [comment]
We have elected to exclude generated code from code coverage tests in projects consuming this plugin rather than generating unit tests on the fly.

Code generation tests should continue to be implemented in this project instead.
