### ISSUE TITLE
HttpHeaderFW.Builder with DirectBuffer values for name/value

### ISSUE THREAD

**Issue by jitsni** [reaktivity/nukleus-maven-plugin#13]
Adding following methods allow to HttpHeaderFW with DirectBuffer. This avoids conversion to String objects when name/value parameters are in DirectBuffer. This needs support in StringFW.Builder issue (https://github.com/reaktivity/nukleus-maven-plugin/issues/12)

```
    public Builder name(DirectBuffer value) {
      name().set(value);
      limit(name().build().limit());
      return this;
    }

    public Builder value(DirectBuffer value) {
      value().set(value);
      limit(value().build().limit());
      return this;
    }
```

**Comment by jitsni** [comment]
Maybe value(DirectBuffer, int, int) would be more generic.

**Comment by jitsni** [comment]
It needs some more change. It should be something like the following (otherwise valueRW.wrap is not called).

```
    public Builder value(DirectBuffer buffer, int offset, int length) {
-      valueRW.set(buffer, offset, length);
+      value().set(buffer, offset, length);
```

**Comment by jfallows** [comment]
Feedback already applied
