### ISSUE TITLE
Need bounded List flyweight 

### ISSUE THREAD

**Issue by jitsni** [reaktivity/nukleus-maven-plugin#17]
Right now, the list flyweight is not bounded. It keeps applying until the buffer's limit is reached. Hence it cannot be composed with other payload.

**Comment by dpwspoon** [comment]
There is an tangental issue where an entry of the list is not bounded.  The forEach method on ListFW uses the limit of the itemRO to iterate each item.  If the itemRO is similarly not bounded (has an octets RO), then this method will not correctly return each itemRO.

```
  public ListFW<T> forEach(Consumer<? super T> consumer) {
    for (int offset = offset() + FIELD_SIZE_LENGTH; offset < limit(); offset = itemRO.limit()) {
      itemRO.wrap(buffer(), offset, limit());
      consumer.accept(itemRO);
    }
    return this;
  }
```

Should we bound each list entry?  Should we require that each itemRO is bounded, and if so should we create a bounded struct type, or change struct to be bounded?

**Comment by jfallows** [comment]
The least intrusive approach is just to require that the list item type is bounded, without changing the binary layout for any of the other types. 

For example, if we need a bounded length octets then a struct with a length field tied to the octets length is sufficient for the list to iterate successfully.
