### ISSUE TITLE
Should authorization field provide method for realm/scope vs roles?

### ISSUE THREAD

**Issue by dpwspoon** [reaktivity/nukleus-maven-plugin#37]
Rather than having the implementation/consuming nukleus magically know the first 2 bytes are the realm/scope, we should provide a method to access to read the first 2 bytes

**Comment by jfallows** [comment]
@cmebarrow did we conclude this is needed or can we safely just treat `authorization` as a bitmask regardless?

**Comment by cmebarrow** [comment]
@jfallows [Current plan](https://docs.google.com/document/d/15uqb6bagNlmJOUNeuJUWxb-H3FwCxBKjxGnF8tAdt8A/edit#heading=h.hr9zrfnvm0z0) is to ensure each realm has its own distinct bit within the 16 realm bits so we can treat the whole authorization as a bit mask. That also has the advantage of allowing us to represent a user being authorized in more than one realm. Obviously the downside is it limits us to 16 realms within a given reaktor. I tried to insulate code from having to make assumptions about this by adding the authorization parameter to the RouteManager.resolve command, in case we need to change it in future.

**Comment by jfallows** [comment]
Leaving as a bitmask rather than forcing any one specific structure for now.
