### ISSUE TITLE
Support varint as built-in type

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-maven-plugin#41]
https://developers.google.com/protocol-buffers/docs/encoding#varints

```
struct VarIntHolder
{
  varint value;
}
```

It should also be possible to use `varint` as a length field to bound `octets`.

```
struct VarIntOctetsHolder
{
  varint length;
  octets[length] data;
}
```

**Comment by cmebarrow** [comment]
* https://developers.google.com/protocol-buffers/docs/encoding?csw=1#simple
    * base 128 varint + zig-zag encoding
    * See Functions.varint method in nukleus-kafka.spec (need to add conversion the other way)

**Comment by cmebarrow** [comment]
@jfallows Can we remove the requirement to support varint as a length field to bound octets? It's very awkward to implement a variable length length field.

**Comment by jfallows** [comment]
Yes, this approach is preferable anyway. 👍

**Comment by cmebarrow** [comment]
Implemented in PR https://github.com/reaktivity/nukleus-maven-plugin/pull/44
