### ISSUE TITLE
Support non-native byte order for generated flyweights

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-maven-plugin#42]
Default to `native` byte order for backwards compatibility and add support for `network` byte order to ease generation of flyweights used to represent network protocols.

Note: scope byte order is inherited by inner scopes, but can still be explicitly overridden as needed.

```
scope outer
{
    option byteorder native* | network;

    scope inner
    {
        struct Holder
        {
            ...
        }       
    }
}
```

**Comment by cmebarrow** [comment]
* in the above indicates the default value
